# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: log_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'log_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11log_service.proto\"\x8f\x01\n\x13LogAsyncTaskRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07task_id\x18\x03 \x01(\t\x12\x0b\n\x03\x65xc\x18\x04 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x05 \x01(\t\x12\x0e\n\x06kwargs\x18\x06 \x01(\t\x12\r\n\x05\x65info\x18\x07 \x01(\t\x12\x0c\n\x04note\x18\x08 \x01(\t\"E\n\x14LogAsyncTaskResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t2N\n\x13LogAsyncTaskService\x12\x37\n\x08WriteLog\x12\x14.LogAsyncTaskRequest\x1a\x15.LogAsyncTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGASYNCTASKREQUEST']._serialized_start=22
  _globals['_LOGASYNCTASKREQUEST']._serialized_end=165
  _globals['_LOGASYNCTASKRESPONSE']._serialized_start=167
  _globals['_LOGASYNCTASKRESPONSE']._serialized_end=236
  _globals['_LOGASYNCTASKSERVICE']._serialized_start=238
  _globals['_LOGASYNCTASKSERVICE']._serialized_end=316
# @@protoc_insertion_point(module_scope)
